Revert changes made for testing

diff --git a/.github/workflows/maia.read_input_file.yml b/.github/workflows/maia.read_input_file.yml
--- a/.github/workflows/maia.read_input_file.yml
+++ b/.github/workflows/maia.read_input_file.yml
@@ -60,7 +60,6 @@ jobs:
       dev_resourcegroup: ${{ steps.read_file.outputs.dev_resourcegroup }}
       dev_datafactory_name: ${{ steps.read_file.outputs.dev_datafactory_name }}
       dev_databricks_kv: ${{ steps.read_file.outputs.dev_databricks_kv }}
-      dev_squad_name: ${{ steps.read_file.outputs.dev_squad_name }}
 
       test_subscriptionid: ${{ steps.read_file.outputs.test_subscriptionid }}
       test_resourcegroup: ${{ steps.read_file.outputs.test_resourcegroup }}
@@ -81,7 +80,7 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
         with:
-          ref: feature/test-input-exceptions
+          ref: main
 
       - name: Read JSON
         id: read_file
@@ -94,7 +93,6 @@ jobs:
           echo ::set-output name=dev_resourcegroup::$(jq -r '.environments.dev.resourcegroup' $FILE_PATH)
           echo ::set-output name=dev_datafactory_name::$(jq -r '.environments.dev.datafactory_name' $FILE_PATH)
           echo ::set-output name=dev_databricks_kv::$(jq -r '.environments.dev.databricks_kv' $FILE_PATH)
-          echo ::set-output name=dev_squad_name::$(jq -r '.environments.dev.squad_name' $FILE_PATH)
 
           echo ::set-output name=test_subscriptionid::$(jq -r '.environments.test.subscriptionid' $FILE_PATH)
           echo ::set-output name=test_resourcegroup::$(jq -r '.environments.test.resourcegroup' $FILE_PATH)
@@ -111,11 +109,11 @@ jobs:
           echo ::set-output name=prod_datafactory_name::$(jq -r '.environments.prod.datafactory_name' $FILE_PATH)
           echo ::set-output name=prod_databricks_kv::$(jq -r '.environments.prod.databricks_kv' $FILE_PATH)
 
-      # - name: Verify valid input parameters
-      #   run: |
-      #     SQUADNAME=${{ steps.read_file.outputs.squad_name }}
+      - name: Verify valid input parameters
+        run: |
+          SQUADNAME=${{ steps.read_file.outputs.squad_name }}
 
-      #     if [[ -z "${SQUADNAME// }" ]]; then
-      #       echo "Invalid squad name inputted: ${SQUADNAME}. Check file ${{inputs.filename}}."
-      #       exit 1
-      #     fi
+          if [[ -z "${SQUADNAME// }" ]]; then
+            echo "Invalid squad name inputted: ${SQUADNAME}. Check file ${{inputs.filename}}."
+            exit 1
+          fi
